### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by HuseyinCoinmerce** [euank/pazi#472]
It looks like there is no more activity on this repository.

@euank is there are reason for this? You don't have time anymore for this project?

all in all, I love this tool, thanks a lot for you work :D

**Comment by euank** [comment]
Glad you've found it useful :D 

There's not much activity, but that's because there haven't been any major bugs or urgent-feeling feature requests.

I still use it, and I'd certainly spend time fixing any important issues that came up... but in practice, it's been working fine for me as-is, so I haven't felt the need to make significant changes anytime recently.

I should do a better job of the background maintenance stuff (keeping dependencies up to date, etc), but it's easy to put those things off, and life's been otherwise keeping me busy.

I'll leave this issue open for the moment as a sorta "go through and at least handle all the dependabot PRs once" issue; do let me know if there's other actionable stuff that you think is warranted!

**Comment by HuseyinCoinmerce** [comment]
So far, I am really happy with it! 😄 I have been using it for a year (or two?).
Thanks for letting me know! I haven't seen any problems so far.

I saw the last release, and my concern was that if there were a bug or security issue, the maintainer wouldn't address it. But that is not a concern anymore :D

**Comment by euank** [comment]
I went ahead and did some basic maintenance work and cut a new release, so I'll go ahead and close this out :smile:
