### ISSUE TITLE
`z init` doesn't work

### ISSUE THREAD

**Issue by euank** [euank/pazi#70]
This issue is suspiciously like #60, but instead of things that autosuggest to something, it's jumps that exactly match something.

This can also be seen in typing `pazi --dir init` which should look for directories containing `init`, but instead prints out help output.

**Comment by euank** [comment]
Unfortunately it seems like there's no way to fix this with the cli structure as it is.

The combination of features interacting are the following:

1. Subcommands (`pazi edit`)
2. A flag + optional flag (`pazi --dir` and `pazi --dir foo -i`)
3. The flags not being well ordered with arguments they may take (e.g. `z -i foo` is `pazi --dir -i foo` and `z foo -i` is `pazi --dir foo -i` and both should work)

I can't find any way to make the above work unfortunately. To have both `pazi --dir -i foo` and `pazi -i --dir foo` work, I end up needing to make `foo` a "trailing" argument instead of a value of "--dir". If it's a value, then `z -i foo` no longer works.

If it's a trailing argument, clap can't distinguish it from a subcommand, so I need a way to do either of the following:

1. Make `--dir` being present imply that no subcommands will work
2. Make `-i` or any other `-flag` not bind to `--dir`'s argument, and then make the target a value of `--dir` (that is, make `pazi --dir -i foo` be treated as if foo is a value of `--dir`)

I'll do one more look through the docs to see if 1. is possible. After laying it out like this in text vs bumbling about with trial and error, it seems worth giving it another look...

If the above all still seems hopeless, I think `--dir` will have to be moved to a subcommand (e.g. `_jump` or something)

**Comment by LinuxMercedes** [comment]
At this point I think the less hacky choice would be to rename `pazi --dir` to `pazi jump`; this would also let us make `-i` a feature of the `jump` subcommand so that, say, `pazi -i init` doesn't work.

If you're (reasonably) concerned about backwards compatibility, I think adding `jump` in addition to `--dir` and switching `pazi init` to use `pazi jump` instead of `pazi --dir`, then removing `--dir` later on would fix most of that problem. Alternatively, we could have any use of `--dir` return with exit code 92 and an error message telling the user to restart their shell.
